// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM-jF0-1hZSrnr1g4g7wCx_OhNso9owVQ',
    appId: '1:886958156619:web:da946d51a0d3a3496196ce',
    messagingSenderId: '886958156619',
    projectId: 'business-finder-2024',
    authDomain: 'business-finder-2024.firebaseapp.com',
    storageBucket: 'business-finder-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOKPSD5pK1mfFM_51pA-Tg3R5OKOVB8U',
    appId: '1:886958156619:android:4123aa4670c6d04d6196ce',
    messagingSenderId: '886958156619',
    projectId: 'business-finder-2024',
    storageBucket: 'business-finder-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyamIZPBXZR63tRGZEF0LMJw6GT8AUHqI',
    appId: '1:886958156619:ios:cdf5b9279f193e386196ce',
    messagingSenderId: '886958156619',
    projectId: 'business-finder-2024',
    storageBucket: 'business-finder-2024.appspot.com',
    iosBundleId: 'com.muler.businessFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM-jF0-1hZSrnr1g4g7wCx_OhNso9owVQ',
    appId: '1:886958156619:web:c6823f492dfa2e9f6196ce',
    messagingSenderId: '886958156619',
    projectId: 'business-finder-2024',
    authDomain: 'business-finder-2024.firebaseapp.com',
    storageBucket: 'business-finder-2024.appspot.com',
  );
}
